# Generated by Django 5.2 on 2025-04-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
